baseURL = "https://lucapette.me"
title = "Home"
summaryLength = 30
enableGitInfo = true
paginate = 5
[params]
  author = 'Luca Pette'
  description = "Luca Pette's website"

[markup]
  [markup.highlight]
    style = 'nord'
[menu]
  [[menu.main]]
    indentifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 100
