baseURL = "https://lucapette.me"
languageCode = "en-us"
title = "Luca Pette"
summaryLength = 30
enableGitInfo = true
paginate = 5
[menu]
  [[menu.main]]
    indentifier = "home"
    name = "Home"
    url = "/"
    weight = 10

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 100
